### ISSUE TITLE
Nothing happened or error when clicking "check" button

### ISSUE THREAD

**Issue by vortexilation** [muink/luci-app-natmapt#2]
I don't get anything when clicking the "check" button, stuntman-client is installed, 
error logged from chrome when clicking "check" button : 
```
Uncaught (in promise) ReferenceError: ui is not defined
    at eval (natmap.js?v=24.158.03388~a6f8361:12:424)
eval @ natmap.js?v=24.158.03388~a6f8361:12
XMLHttpRequest.send (async)
(anonymous) @ luci.js?v=24.158.03388~a6f8361:66
(anonymous) @ luci.js?v=24.158.03388~a6f8361:47
Promise.then (async)
request @ luci.js?v=24.158.03388~a6f8361:47
flushRequestQueue @ luci.js?v=24.158.03388~a6f8361:39
requestAnimationFrame (async)
(anonymous) @ luci.js?v=24.158.03388~a6f8361:50
(anonymous) @ luci.js?v=24.158.03388~a6f8361:47
Promise.then (async)
request @ luci.js?v=24.158.03388~a6f8361:47
post @ luci.js?v=24.158.03388~a6f8361:71
call @ rpc.js?v=24.158.03388~a6f8361:5
eval @ rpc.js?v=24.158.03388~a6f8361:23
eval @ rpc.js?v=24.158.03388~a6f8361:20
exec @ fs.js?v=24.158.03388~a6f8361:11
o.onclick @ natmap.js?v=24.158.03388~a6f8361:12
eval @ form.js?v=24.158.03388~a6f8361:260
eval @ ui.js?v=24.158.03388~a6f8361:360Understand this error
```

![image](https://github.com/muink/luci-app-natmapt/assets/60100560/65d44b36-6530-467b-a341-9f8af1cf6896)

**Comment by muink** [comment]
Try https://github.com/muink/luci-app-natmapt/commit/fcb4e3b066d8376c61a44f4cb57e6933e45911cb

**Comment by vortexilation** [comment]
Thank you, but now getting "Permission denied" error.

**Comment by vortexilation** [comment]
I need to make natcheck.sh as a binary then I can use the "Check" button : 
```
chmod +x /usr/libexec/natmap/natcheck.sh
```

**Comment by muink** [comment]
`natcheck.sh` in the pre-built ipk already has `755` permissions set, so I'm not sure why you would need to re-grant permissions.
<img width="773" alt="image" src="https://github.com/muink/luci-app-natmapt/assets/7929014/9927e869-85fc-4a5d-b53b-d97bbe9eeba5">

**Comment by vortexilation** [comment]
I am downloading luci-app-natmapt into a windows machine and re-uploaded it into my OpenWrt build server, perhaps the permission is lost when at windows machine.

Closing this one as completed.
