### ISSUE TITLE
大佬，DDNS cloudflare 下面只有A记录，没有AAAA记录填写位置，AAAA记录要怎么填？谢谢

### ISSUE THREAD

**Issue by YunHair** [muink/luci-app-natmapt#3]
大佬，DDNS cloudflare 下面只有A记录，没有AAAA记录填写位置，AAAA记录要怎么填？谢谢

**Comment by muink** [comment]
AAAA 记录仅在 IPv6 模式下可用
![image](https://github.com/user-attachments/assets/b5549dd3-b1d8-42ec-915b-610fec714412)

**Comment by muink** [comment]
把你的 cf 的 `TOKEN` 和 `ZONE_ID` 填上去
再把要设定的 `你的域名` 写上去
![image](https://github.com/user-attachments/assets/1871b609-076c-47e9-830d-931fbc927a52)

**Comment by YunHair** [comment]
哦，明白了，谢谢
